name: Setup WORKSPACE_ROOT
description: Set WORKSPACE_ROOT for powershell scripts

runs:
  using: "composite"
  steps:
    - name: Set WORKSPACE_ROOT if not already set
      shell: bash
      run: |
        if [ -z "$WORKSPACE_ROOT" ]; then
          echo "WORKSPACE_ROOT=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "✅ WORKSPACE_ROOT set to: $GITHUB_WORKSPACE"
        else
          echo "ℹ️ WORKSPACE_ROOT already set to: $WORKSPACE_ROOT"
        fi