name: Build Setup
description: Setup dotnet SDK

runs:
  using: "composite"
  steps:
    - name: Set WORKSPACE_ROOT
      uses: ./.github/actions/setup-workspace-root

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'