name: Acceptance Stage

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-acceptance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup requirements to build and test
      uses: ./.github/actions/build-setup

    - name: Setup requirements to deploy
      uses: ./.github/actions/gcloud-setup
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

    - name: Run acceptance stage script
      shell: pwsh
      run: |
        ./scripts/stages/acceptance.ps1 -Version "${{ github.sha }} -IpInfoToken ${{ secrets.IPINFO_TOKEN }}"
