name: Acceptance Stage

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-acceptance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run acceptance stage script in dev container
      uses: devcontainers/ci@v0.3

      with:
        cacheFrom: ghcr.io/curlyfire/ctf-sandbox-devcontainer
        runCmd: |
          set -euo pipefail

          # Feed the JSON secret directly to gcloud via stdin
          cat <<'EOF' | gcloud auth activate-service-account \
            --key-file=- \
            --project "${{ secrets.GCP_PROJECT_ID }}"
          ${{ secrets.GCP_SA_KEY }}
          EOF
          
          # Configure Docker auth non-interactively
          gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev" --quiet

          VERSION="${{ github.sha }}"
          ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}"
          IPINFO_TOKEN="${{ secrets.IPINFO_TOKEN }}"

          psArgs_base=(
            "-Version" "$VERSION"
            "-AdminPassword" "$ADMIN_PASSWORD"
            "-IpInfoToken" "$IPINFO_TOKEN"
          )

          pwsh -Command "./pipelines/stages/acceptance/invoke.ps1 ${psArgs_base[@]}