name: Acceptance Stage

on:
  schedule:
    - cron: '0 * * * *'  # Every hour
  workflow_dispatch:

jobs:
  run-acceptance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Acceptance Stage Script in dev container
      uses: ./.github/actions/run-in-gcloud-authenticated-devcontainer
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_sa_key_base64: ${{ secrets.GCP_SA_KEY_BASE64 }}
        gcp_region: ${{ secrets.GCP_REGION }}

        run_command: |
          pwsh ./pipelines/stages/acceptance/invoke.ps1 \
          -Version ${{ github.sha }} \
          -AdminPassword ${{ secrets.ADMIN_PASSWORD }} \
          -IpInfoToken  ${{ secrets.IPINFO_TOKEN }} \
          -WebAdminAccount ${{ secrets.WEB_ADMIN_ACCOUNT }} \
          -MailpitAdminAccount ${{ secrets.MAILPIT_ADMIN_ACCOUNT }} ${{ github.event_name == 'workflow_dispatch' && '-Force' || '' }}
