name: Commit stage CD

on:
  workflow_run:
    workflows: ["Commit stage CI"]
    types:
      - completed

jobs:
  deploy-to-acceptance:
    name: CD / Deploy to Acceptance
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ github.event.workflow_run.head_sha }}
      environment: acceptance
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_REGION: ${{ secrets.GCP_REGION }}