name: Commit stage CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
permissions:
  checks: write
  contents: read
  
jobs:
  build-and-test:
    name: CI / Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build -c Release ./src

    - name: Run unit tests
      run: dotnet test --no-build -c Release --logger "trx;LogFilePath=unit-test-results.trx" --filter "Category=Unit" ./src

    - name: Run narrow integration tests
      run: dotnet test --no-build -c Release --logger "trx;LogFilePath=narrow-integration-test-results.trx" --filter "Category=NarrowIntegration" ./src

    - name: Run component tests
      run: dotnet test --no-build -c Release --logger "trx;LogFilePath=component-test-results.trx" --filter "Category=Component" ./src

    - name: Run contract verification tests
      run: dotnet test --no-build -c Release --logger "trx;LogFilePath=contract-verification-test-results.trx" --filter "Category=ContractVerification" ./src

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v2
      if: github.event_name == 'push'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      if: github.event_name == 'push'
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Configure Docker to use gcloud credentials
      if: github.event_name == 'push'
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    
    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ctf-sandbox-repo/ctf-sandbox:latest"
        docker push $IMAGE