name: Commit stage

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
permissions:
  checks: write
  contents: read
  
jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Google Cloud SDK, GKE Auth Plugin and dotnet SDK
      uses: ./.github/actions/setup
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build, Test and Publish
      shell: pwsh
      run: ./scripts/commit-stage/build-test-publish.ps1

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/*.trx'
        reporter: dotnet-trx

    - name: Build Docker image
      shell: pwsh
      run: ./scripts/commit-stage/build-docker.ps1 -ProjectId "${{ secrets.GCP_PROJECT_ID }}" -ImageTag "${{ github.sha }}"
    
    - name: Push Docker image
      if: github.event_name == 'push'
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ctf-sandbox-repo/ctf-sandbox:${{ github.sha }}"
        docker push $IMAGE