name: Commit stage

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
permissions:
  checks: write
  contents: read
jobs:
  build-and-test:
    name: CI / Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup requirements to build and test
      uses: ./.github/actions/build-setup

    - name: Setup requirements to deploy
      uses: ./.github/actions/deploy-setup
      with:
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
      if: github.event_name == 'push'

    - name: Set Image Name
      shell: pwsh
      run: |
        $fullImageName = "${{ secrets.GCP_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ vars.GCP_REPOSITORY }}/${{ vars.IMAGE_NAME }}"
        "FULL_IMAGE_NAME=$fullImageName" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        Write-Host "✅ FULL_IMAGE_NAME set to: $fullImageName"      

    - name: Build, Test and Publish (All runs)
      shell: pwsh
      run: |
        ./scripts/commit-stage/build-test-publish.ps1 `
          -ImageName "$env:FULL_IMAGE_NAME" `
          -ImageTag "${{ github.sha }}"

    - name: Build, Test and Push (Only on Push)
      if: github.event_name == 'push'
      shell: pwsh
      run: |
        ./scripts/commit-stage/build-test-publish.ps1 `
          -ImageName "$env:FULL_IMAGE_NAME" `
          -ImageTag "$env:IMAGE_TAG" `
          -PushImage

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/*.trx'
        reporter: dotnet-trx