name: Commit stage

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    name: CI / Build and Test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Build
      run: dotnet build -c Release ./src

    - name: Run tests
      run: dotnet test --no-build -c Release --logger "trx;LogFilePath=test-results.trx" ./src

    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: .NET Tests
        path: '**/TestResults/*.trx'
        reporter: dotnet-trx

    - name: Publish UI
      run: dotnet publish --no-build -c Release -o ./publish ./src/ctf-sandbox.csproj
    
    - name: Upload publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish-output
        path: ./publish

  push:
    name: CD / Docker Push
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4      

    - name: Download publish artifacts
      uses: actions/download-artifact@v4
      with:
        name: publish-output
        path: ./publish

    - name: Login to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ctf-sandbox-repo/ctf-sandbox:latest"
        docker build -t $IMAGE .
        docker push $IMAGE