# This workflow split is required to have badges available for the production environment
name: Production stage

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image SHA to deploy"
        required: true
        type: string

jobs:
  call-release:
    uses: ./.github/workflows/release.yml
    secrets: 
        inherit
    with:
      environment: prod
      version: ${{ inputs.version }}