name: QA Signoff

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that was tested in QA (e.g., v1.0.4-rc)'
        required: true
        type: string
      success:
        description: 'QA testing was successful (check if it was)'
        required: true
        type: boolean
permissions:
  contents: write
  packages: write
jobs:
  qa-signoff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
          
      # TODO: IF GETTING ERROR HTTP 403: Resource not accessible by integration
      # THEN ADD PAT like mentionned here: https://github.com/cli/cli/issues/9514
      # Seems related to releasing an older commit that is not HEAD
      - name: Run qa-signoff Stage Script in dev container
        uses: ./.github/actions/run-in-gcloud-authenticated-devcontainer
        with:
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_sa_key_base64: ${{ secrets.GCP_SA_KEY_BASE64 }}
          gcp_region: ${{ secrets.GCP_REGION }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}

          run_command: |
            pwsh ./pipelines/stages/qa-signoff/invoke.ps1 \
            -Version ${{ inputs.version }}  ${{ inputs.success == true && '-Success' || '' }}