name: QA Signoff

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version that was tested in QA (e.g., v1.0.4-rc)'
        required: true
        type: string
      success:
        description: 'Was QA testing successful? (true/false)'
        required: true
        type: boolean
permissions:
  contents: write
jobs:
  qa-signoff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Run QA Signoff Stage Script in dev container
        uses: ./.github/actions/run-in-gcloud-authenticated-devcontainer
        with:
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_sa_key_base64: ${{ secrets.GCP_SA_KEY_BASE64 }}
          gcp_region: ${{ secrets.GCP_REGION }}

          run_command: |
            pwsh -Command "./pipelines/stages/qa-signoff/invoke.ps1 -Version ${{ inputs.version }} -Success \$${{ inputs.success }}"
