name: QA Signoff

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write
jobs:
  qa-signoff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags
          
      - name: Test
        run: git tag v0.0.1 3c2f0f4df281900efb4d95855860274ab1342d20 && git push origin v0.0.1