# This workflow split is required to have badges available for the uat environment
name: Deploy to UAT

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image SHA to deploy"
        required: true
        type: string

jobs:
  call-release:
    uses: ./.github/workflows/release-stage.yml
    secrets: 
        inherit
    with:
      environment: uat
      version: ${{ inputs.version }}