name: Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  resolve-url:
    runs-on: ubuntu-latest
    outputs:
      mvc_url: ${{ steps.set-url.outputs.mvc_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup requirements to interact with Google Cloud
        uses: ./.github/actions/gcloud-setup
        with:
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

      - name: Extract and set MVC App URL
        id: set-url
        shell: pwsh
        run: |
          $projectNumber = & gcloud projects describe "${{ secrets.GCP_PROJECT_ID }}" --format='value(projectNumber)'
          $mvcUrl = "https://mvc-app-${{ github.event.inputs.environment }}-$projectNumber.${{ secrets.GCP_REGION }}.run.app"
          "mvc_url=$mvcUrl" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append


  deploy:
    needs: resolve-url
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ needs.resolve-url.outputs.mvc_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup requirements to deploy
        uses: ./.github/actions/gcloud-setup
        with:
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_sa_key: ${{ secrets.GCP_SA_KEY }}        

      - name: Run release script
        shell: pwsh
        run: |
          ./scripts/release-gcloud.ps1 `
            -Version "${{ inputs.version }}" `
            -Region "${{ secrets.GCP_REGION }}" `
            -Project "${{ secrets.GCP_PROJECT_ID }}" `
            -Env "${{ inputs.environment }}" `
            -AdminPassword "${{ secrets.ADMIN_PASSWORD }}"

      - name: Run smoke tests
        run: dotnet test -c Release --logger "trx;LogFilePath=smoke-test-results.trx" --filter "Category=Smoke" ./src
