name: Save money

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours
  workflow_dispatch:

jobs:
  run-teardown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run save money script in dev container
        uses: devcontainers/ci@v0.3

        with:
          cacheFrom: ghcr.io/curlyfire/ctf-sandbox-devcontainer
          runCmd: |
            set -euo pipefail

            # Feed the JSON secret directly to gcloud via stdin
            cat <<'EOF' | gcloud auth activate-service-account \
              --key-file=- \
              --project "${{ secrets.GCP_PROJECT_ID }}"
            ${{ secrets.GCP_SA_KEY }}
            EOF
            
            # Configure Docker auth non-interactively
            gcloud auth configure-docker "${{ secrets.GCP_REGION }}-docker.pkg.dev" --quiet

            pwsh -Command "./pipelines/teardown-all-gcloud.ps1"